name: Snakemake-Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  snakemake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Snakemake dry run
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: '.'
          args: '-np'

      - name: Create container file
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: '.'
          task: 'containerize'
